# Generated by Django 5.2.12 on 2026-04-06 15:36

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_comment_parent_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[common.validators.validate_image_file]),
        ),
    ]
